server:
  port: 8761

spring:
  application:
    name: discovery-server
  profiles:
    active: dev

eureka:
  instance:
    hostname: discovery-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    com.ehealth: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
